version: "3"
services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./:/app
    depends_on:
      - postgres
    environment:
      DB_CONNECTION: ${DB_CONNECTION}
      DB_HOST: ${DB_HOST}
      DB_PORT: 5432
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: 9871237645
      RUN_MIGRATIONS: "true"
      APP_ENV: "local"
      APP_DEBUG: "true"
      LOG_CHANNEL: "stderr"
    entrypoint: ["sh", "entrypoint.sh"]

  worker:
    build:
      context: .
      dockerfile: Dockerfile
    command: php artisan queue:work
    depends_on:
      - app
    volumes:
      - ./:/app
    environment:
      DB_CONNECTION: ${DB_CONNECTION}
      DB_HOST: ${DB_HOST}
      DB_PORT: 5432
      DB_DATABASE: ${DB_DATABASE}
      DB_USERNAME: ${DB_USERNAME}
      DB_PASSWORD: 9871237645
      APP_ENV: "local"

  postgres:
    image: postgres:13
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: 9871237645
    volumes:
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata:
